services:
  - type: web
    name: pdf-splitter-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app --timeout 300 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
